include: package:very_good_analysis/analysis_options.yaml

# https://dart.dev/tools/analysis#changing-the-severity-of-rules
analyzer:
  plugins:
    - custom_lint
  errors:
    depend_on_referenced_packages: error
    # Ignore till the lint rule runs well on Dart >= 3.7.
    require_trailing_commas: ignore
    # Now we adjust the maximum line to 120
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.mapper.dart
    - packages/**

formatter:
  page_width: 120

linter:
  rules:
    flutter_style_todos: false