name: flutter_bbcode_editor
description: Edit bbcode with WYSIWYG support
repository: 'https://github.com/realth000/flutter_bbcode_editor'
issue_tracker: 'https://github.com/realth000/flutter_bbcode_editor/issues'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.2.0

dependencies:
  appflowy_editor: ^2.4.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  universal_html: ^2.2.4
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

