name: flutter_bbcode_editor
description: Edit bbcode with WYSIWYG support
repository: 'https://github.com/realth000/flutter_bbcode_editor'
issue_tracker: 'https://github.com/realth000/flutter_bbcode_editor/issues'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.2.0

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

