name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CI_FLUTTER_VERSION: '3.29.x'

jobs:
  flutter_test:
    name: Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Precompile
        run: |
          git submodule update --init --recursive --force
          flutter pub get
      - name: Run flutter analyze
        run: |
          flutter analyze --fatal-infos --fatal-warnings lib
      - name: Run flutter test
        run: |
          flutter test
