name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CI_FLUTTER_VERSION: '3.29.x'

jobs:
  flutter_test:
    name: Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Precompile
        run: |
          git submodule update --init --recursive --force
          sed -i 's#    path: ../../../dart_bbcode_web_colors#    path: ../dart_bbcode_web_colors#g' packages/flutter-quill/pubspec.yaml
          sed -i 's#    path: ../dart_bbcode_web_colors#    path: packages/dart_bbcode_web_colors#g' pubspec.yaml
          sed -i 's#    path: ../dart_bbcode_parser#    path: packages/dart_bbcode_parser#g' pubspec.yaml
          git clone https://github.com/realth000/dart_bbcode_web_colors.git packages/dart_bbcode_web_colors
          git clone https://github.com/realth000/dart_bbcode_parser.git packages/dart_bbcode_parser
          flutter pub get
      - name: Run flutter analyze
        run: |
          flutter analyze --fatal-infos --fatal-warnings lib
      - name: Run flutter test
        run: |
          flutter test
